Extend appinfo configuration
Samsung/grunt-cordova-sectv pull request #12
Opened 2017-07-06 21:28 UTC by drahosistvan

On WebOS, you are able to configure application icon background, splash screen, and hover image from appinfo.json.
With this pull request, developers are able to configure the webOS builds better.

This pull request is connected to my [cordova-tv-webos](https://github.com/Samsung/cordova-tv-webos/pull/1) request.

2017-07-07 00:07 UTC, prozanne requested changes
Would you consider these reviews?

2017-07-07 00:07 UTC, prozanne commented on tasks/packager/tv-webos.js
> +    console.log('      > bgColor            : ' + userData.bgcolor);
We decided to show stored information only for mandatory items we think.
If all kind of attributes are shown, log might be complex.

So, can you rollback this to have only id, name, version, vendor, resolution as previous?

2017-07-07 00:07 UTC, prozanne commented on tasks/packager/tv-webos.js
> +            default: 'red',
Could you change default color to white or black (achromatic color)?
I think it's better to have an inconspicuous color.

2017-07-07 00:07 UTC, prozanne commented on tasks/packager/tv-webos.js
> +            default: 'red',
Could you change default color to white or black (achromatic color)?
I think it's better to have an inconspicuous color.

2017-07-07 07:40 UTC, drahosistvan commented on tasks/packager/tv-webos.js
> +    console.log('      > bgColor            : ' + userData.bgcolor);
I modified the console log. Now, it is untouched.

2017-07-07 07:41 UTC, drahosistvan commented on tasks/packager/tv-webos.js
> +            default: 'red',
Default color is modified to white.

2017-07-07 07:41 UTC, drahosistvan commented on tasks/packager/tv-webos.js
> +            default: 'red',
Default color is modified to white.

2017-07-09 23:40 UTC, prozanne approved these changes
Thank you for your contribution!!!

2017-07-09 23:42 UTC, merged